In [91]:
import sklearn 
from sklearn.utils import shuffle 
from sklearn.neighbors import KNeighborsClassifier 
import pandas as pd 
import numpy as np 
from sklearn import linear_model, preprocessing 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import f1_score 
from sklearn.metrics import accuracy_score 

In [92]:

data = pd.read_csv("car.data")
print(data.head())


  buying  maint door persons lug_boot safety  class
0  vhigh  vhigh    2       2    small    low  unacc
1  vhigh  vhigh    2       2    small    med  unacc
2  vhigh  vhigh    2       2    small   high  unacc
3  vhigh  vhigh    2       2      med    low  unacc
4  vhigh  vhigh    2       2      med    med  unacc


In [93]:
le = preprocessing.LabelEncoder() 

buying = le.fit_transform(list(data["buying"])) 

maint = le.fit_transform(list(data["maint"])) 

door = le.fit_transform(list(data["door"])) 

persons = le.fit_transform(list(data["persons"])) 

lug_boot = le.fit_transform(list(data["lug_boot"])) 

safety = le.fit_transform(list(data["safety"])) 

cls = le.fit_transform(list(data["class"])) 

In [95]:
predict = "class" 
x = list(zip(buying, maint, door, persons, lug_boot, safety)) 
y = list (cls) 

 

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size=0.1) 

print (x_train, y_test) 

[(2, 1, 2, 1, 0, 0), (0, 2, 2, 0, 2, 1), (1, 2, 2, 2, 0, 2), (0, 3, 1, 1, 0, 1), (2, 0, 1, 2, 0, 2), (3, 1, 1, 1, 2, 0), (1, 1, 3, 0, 1, 0), (2, 1, 3, 0, 0, 1), (3, 3, 3, 2, 1, 2), (2, 1, 2, 2, 2, 1), (1, 3, 3, 0, 0, 2), (3, 1, 2, 0, 1, 0), (1, 1, 1, 1, 2, 2), (0, 1, 3, 1, 2, 1), (0, 1, 0, 2, 2, 1), (3, 2, 1, 0, 1, 0), (2, 1, 3, 1, 2, 0), (2, 3, 2, 2, 2, 0), (2, 1, 2, 2, 1, 1), (2, 2, 1, 2, 0, 2), (1, 3, 3, 0, 1, 1), (1, 3, 1, 2, 2, 2), (2, 0, 0, 0, 1, 2), (2, 1, 1, 2, 0, 0), (2, 3, 2, 2, 1, 0), (0, 0, 0, 0, 2, 2), (3, 1, 3, 0, 0, 0), (3, 0, 0, 0, 2, 0), (0, 2, 3, 0, 0, 2), (1, 1, 3, 2, 2, 0), (3, 1, 3, 1, 1, 1), (3, 0, 2, 1, 0, 1), (0, 0, 0, 1, 2, 0), (3, 0, 1, 0, 0, 2), (3, 3, 0, 1, 0, 2), (0, 0, 1, 2, 2, 2), (2, 2, 0, 2, 1, 0), (1, 3, 2, 0, 2, 0), (3, 3, 0, 1, 0, 1), (0, 1, 3, 0, 2, 0), (0, 0, 1, 0, 0, 1), (1, 0, 2, 0, 0, 2), (2, 1, 0, 2, 2, 2), (1, 2, 2, 2, 1, 2), (0, 0, 0, 1, 2, 2), (0, 3, 3, 0, 1, 2), (3, 0, 0, 2, 1, 2), (1, 2, 2, 1, 0, 1), (2, 1, 0, 2, 1, 1), (0, 2, 2, 2, 0, 2),

In [96]:
model = KNeighborsClassifier(metric='euclidean', p=3,  n_neighbors=9) 

model.fit(x_train, y_train) 

acc = model.score(x_test, y_test) 

print(acc) 

0.9075144508670521


In [97]:
y_pred = model.predict(x_test)
y_pred

array([2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2,
       2, 3, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 0, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 1, 0, 2, 0,
       0, 0, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0,
       1, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 2, 0, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 0, 0,
       0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [98]:
predicted = model.predict(x_test)
names = ["unnac", "acc", "good", "vgood"]
for x in range (len(predicted)):
    print("predicted: ", names[predicted[x]], "Data:", x_test[x], "actual: ", names[y_test[x]])
    n = model.kneighbors([x_test[x]], 9, True)
print("N: ", n)

predicted:  good Data: (3, 2, 0, 0, 2, 1) actual:  good
predicted:  good Data: (1, 3, 3, 1, 1, 1) actual:  good
predicted:  good Data: (1, 1, 0, 0, 0, 2) actual:  good
predicted:  good Data: (1, 1, 1, 2, 0, 1) actual:  good
predicted:  good Data: (1, 2, 3, 1, 2, 2) actual:  unnac
predicted:  unnac Data: (0, 1, 2, 1, 2, 0) actual:  unnac
predicted:  unnac Data: (0, 2, 1, 1, 2, 0) actual:  unnac
predicted:  good Data: (1, 0, 1, 2, 2, 2) actual:  unnac
predicted:  good Data: (3, 2, 0, 1, 0, 2) actual:  unnac
predicted:  good Data: (0, 2, 3, 1, 2, 1) actual:  good
predicted:  good Data: (3, 2, 3, 2, 0, 1) actual:  good
predicted:  good Data: (2, 3, 1, 2, 0, 1) actual:  good
predicted:  good Data: (3, 3, 3, 2, 0, 2) actual:  good
predicted:  good Data: (1, 3, 2, 2, 2, 1) actual:  good
predicted:  good Data: (2, 0, 1, 1, 1, 1) actual:  good
predicted:  good Data: (3, 3, 3, 2, 1, 1) actual:  good
predicted:  good Data: (0, 2, 0, 0, 0, 1) actual:  good
predicted:  unnac Data: (3, 1, 1, 1, 1, 0

In [99]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

print(accuracy_score(y_test, y_pred))




[[ 35   0  12   0]
 [  3   3   0   0]
 [  1   0 117   0]
 [  0   0   0   2]]
0.9075144508670521
